### ISSUE TITLE
I am very sorry to borrow this issue.

### ISSUE THREAD

**Issue by a-jie** [JPeer264/node-json-extra#2]
Because I forgot your practice, sorry.

![image](https://user-images.githubusercontent.com/3407208/67175671-a6104080-f3f9-11e9-9976-4c117951a5ec.png)

https://projects.jpeer.at/proton/

The document you wrote for proton seems to be inaccessible. You can put him under your `github page`, and if that is the case, there should be no problem.

thank you very much!

**Comment by JPeer264** [comment]
Hey  Oh that's not good. I will put it to Github pages :) This may take one or two days, as I am currently not on a laptop.

**Comment by a-jie** [comment]
thank

**Comment by JPeer264** [comment]
The problem is solved now :)
